[project]
name = "docker-repro-pixi-install-to-prefix"
description = "pixi-install-to-prefix demo env"
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64"]

[dependencies]
pixi-install-to-prefix = "*"
