[package]
name = "pixi-install-to-prefix"
description = "Install pixi environments to an arbitrary prefix"
version = "0.0.1"
edition = "2024"

# See https://doc.rust-lang.org/cargo/reference/profiles.html
[profile.release]
codegen-units = 1
lto = true
strip = true
opt-level = "z"

[features]
default = ["native-tls"]
native-tls = [
  "reqwest/native-tls",
  "reqwest/native-tls-alpn",
  "rattler/native-tls",
  "rattler_networking/rustls-tls",
  "rattler_package_streaming/rustls-tls",
]
rustls-tls = [
  "reqwest/rustls-tls",
  "reqwest/rustls-tls-native-roots",
  "rattler/rustls-tls",
  "rattler_networking/rustls-tls",
  "rattler_package_streaming/rustls-tls",
]

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.37", features = ["derive", "string"] }
clap-verbosity-flag = { version = "3.0.2", features = ["tracing"] }
# TODO: use pixi_config crate
pixi_config = { git = "https://github.com/prefix-dev/pixi", branch = "main" }
rattler = { version = "0.33.5", default-features = false }
rattler_digest = "1.1.1"
rattler_conda_types = "0.32.0"
rattler_index = "0.22.5"
rattler_lock = "0.23.2"
rattler_networking = { version = "0.22.12", default-features = false }
rattler_package_streaming = { version = "0.22.36", default-features = false }
rattler_shell = "0.22.26"
reqwest = { version = "0.12.15", default-features = false, features = [
  "http2",
  "macos-system-configuration",
] }
reqwest-middleware = "0.4.2"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
serde_yaml = "0.9.34"
tokio = { version = "1.44.2", features = ["rt-multi-thread"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = [
  "default",
  "env-filter",
] }

[dev-dependencies]
rstest = "0.25.0"
