[project]
name = "pixi-inject-to-prefix"
channels = ["conda-forge"]
platforms = [
  "osx-arm64",
  "osx-64",
  "linux-64",
  "linux-aarch64",
  "win-64",
  # wait for win-arm64 packages to be available
  # https://github.com/conda-forge/conda-forge.github.io/issues/1940
  # "win-arm64",
]

[tasks]
build = "cargo build --release"
test = "cargo test"

[dependencies]
rust = "==1.86.0"
openssl = "3.*"
pkg-config = "*"

[target.linux.dependencies]
compilers = ">=1.7.0"

[feature.lint.dependencies]
pre-commit = "*"
prettier = "*"
taplo = "*"
pre-commit-hooks = "*"
typos = "*"
shellcheck = "*"
[feature.lint.tasks]
pre-commit-install = "pre-commit install"
pre-commit-run = "pre-commit run -a"

[environments]
lint = { features = ["lint"], no-default-feature = true }
