[project]
name = "test-project"
channels = ["conda-forge"]
platforms = [
  "osx-arm64",
  "osx-64",
  "linux-64",
  "linux-aarch64",
  "linux-ppc64le",
  "win-64",
]

[dependencies]
python = ">=3.12"
openssl = "*"
